name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: clonging repo
        uses: actions/checkout@v3
      - name: my-step
        run: echo "application_env=staging"
        id: my-name
      - name: tell me the directory I am in
        run: |
        echo "ji"
        echo applcation_env=${{steps.my-name.outputs}} 
      - name: count the number in a file
        run: wc -m hello


        outputs: 

