name: hello-world
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.my-orginal.outputs.TEST }}

    steps:
      - id: my-orginal
        run: |
          echo "TEST=grades" >> $GITHUB_OUTPUT
          echo "MATH=exams"  >> $GITHUB_OUTPUT
      - name: my-example
        run: echo ${{steps.my-orginal.outputs.TEST}}/${CRA}

env:
  CRA: ali

