name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: clonging repo
        uses: actions/checkout@v3
      - name: my-step
        run: echo "application_env=staging"
      - name: tell me the directory I am in
        run: |
          echo APPLICATION_ENV="test_var" >> $GITHUB_ENV
      - name: count the number in a file
        run: |
          wc -m hello
          echo $APPLICATION_ENV






echo PR_NUMBER=$(gh pr view --json number -q .number) >> $GITHUB_ENV